using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WcsParis
{
    public class cTagPlc
    {
        public string string01 { get; set; }
        public string string02 { get; set; }
        public string string03 { get; set; }
        public string string04 { get; set; }
        public string string05 { get; set; }
        public string string06 { get; set; }
        public string string07 { get; set; }
        public string string08 { get; set; }
        public string string09 { get; set; }
        public string string010 { get; set; }

        public int int01 { get; set; }
        public int int02 { get; set; }
        public int int03 { get; set; }
        public int int04 { get; set; }
        public int int05 { get; set; }
        public int int06 { get; set; }
        public int int07 { get; set; }
        public int int08 { get; set; }
        public int int09 { get; set; }
        public int int10 { get; set; }

        public bool bool01 { get; set; }
        public bool bool02 { get; set; }
        public bool bool03 { get; set; }
        public bool bool04 { get; set; }
        public bool bool05 { get; set; }
        public bool bool06 { get; set; }
        public bool bool07 { get; set; }
        public bool bool08 { get; set; }
        public bool bool09 { get; set; }
        public bool bool10 { get; set; }
        public bool bool11 { get; set; }
        public bool bool12 { get; set; }
        public bool bool13 { get; set; }
        public bool bool14 { get; set; }
        public bool bool15 { get; set; }
        public bool bool16 { get; set; }
        public bool bool17 { get; set; }
        public bool bool18 { get; set; }
        public bool bool19 { get; set; }
        public bool bool20 { get; set; }
        public bool bool21 { get; set; }
        public bool bool22 { get; set; }
        public bool bool23 { get; set; }
        public bool bool24 { get; set; }
        public bool bool25 { get; set; }
        public bool bool26 { get; set; }
        public bool bool27 { get; set; }
        public bool bool28 { get; set; }
        public bool bool29 { get; set; }
        public bool bool30 { get; set; }
        public bool bool31 { get; set; }
        public bool bool32 { get; set; }
        public bool bool33 { get; set; }
        public bool bool34 { get; set; }
        public bool bool35 { get; set; }
        public bool bool36 { get; set; }
        public bool bool37 { get; set; }
        public bool bool38 { get; set; }
        public bool bool39 { get; set; }
        public bool bool40 { get; set; }
        public bool bool41 { get; set; }
        public bool bool42 { get; set; }
        public bool bool43 { get; set; }
        public bool bool44 { get; set; }
        public bool bool45 { get; set; }
        public bool bool46 { get; set; }
        public bool bool47 { get; set; }
        public bool bool48 { get; set; }
        public bool bool49 { get; set; }
        public bool bool50 { get; set; }
        public bool bool51 { get; set; }
        public bool bool52 { get; set; }
        public bool bool53 { get; set; }
        public bool bool54 { get; set; }
        public bool bool55 { get; set; }
        public bool bool56 { get; set; }
        public bool bool57 { get; set; }
        public bool bool58 { get; set; }
        public bool bool59 { get; set; }
        public bool bool60 { get; set; }
        public bool bool61 { get; set; }
        public bool bool62 { get; set; }
        public bool bool63 { get; set; }
        public bool bool64 { get; set; }
        public bool bool65 { get; set; }
        public bool bool66 { get; set; }
        public bool bool67 { get; set; }
        public bool bool68 { get; set; }
        public bool bool69 { get; set; }
        public bool bool70 { get; set; }
        public bool bool71 { get; set; }
        public bool bool72 { get; set; }
        public bool bool73 { get; set; }
        public bool bool74 { get; set; }
        public bool bool75 { get; set; }
        public bool bool76 { get; set; }
        public bool bool77 { get; set; }
        public bool bool78 { get; set; }
        public bool bool79 { get; set; }
        public bool bool80 { get; set; }
        public bool bool81 { get; set; }
        public bool bool82 { get; set; }
        public bool bool83 { get; set; }
        public bool bool84 { get; set; }
        public bool bool85 { get; set; }
        public bool bool86 { get; set; }
        public bool bool87 { get; set; }
        public bool bool88 { get; set; }
        public bool bool89 { get; set; }
        public bool bool90 { get; set; }
        public bool bool91 { get; set; }
        public bool bool92 { get; set; }
        public bool bool93 { get; set; }
        public bool bool94 { get; set; }
        public bool bool95 { get; set; }
        public bool bool96 { get; set; }
        public bool bool97 { get; set; }
        public bool bool98 { get; set; }
        public bool bool99 { get; set; }
        public bool bool100 { get; set; }
        public bool bool101 { get; set; }
        public bool bool102 { get; set; }
        public bool bool103 { get; set; }
        public bool bool104 { get; set; }
        public bool bool105 { get; set; }
        public bool bool106 { get; set; }
        public bool bool107 { get; set; }
        public bool bool108 { get; set; }
        public bool bool109 { get; set; }
        public bool bool110 { get; set; }
        public bool bool111 { get; set; }
        public bool bool112 { get; set; }
        public bool bool113 { get; set; }
        public bool bool114 { get; set; }
        public bool bool115 { get; set; }
        public bool bool116 { get; set; }
        public bool bool117 { get; set; }
        public bool bool118 { get; set; }
        public bool bool119 { get; set; }
        public bool bool120 { get; set; }
        public bool bool121 { get; set; }
        public bool bool122 { get; set; }
        public bool bool123 { get; set; }
        public bool bool124 { get; set; }
        public bool bool125 { get; set; }
        public bool bool126 { get; set; }
        public bool bool127 { get; set; }
        public bool bool128 { get; set; }
        public bool bool129 { get; set; }
        public bool bool130 { get; set; }
        public bool bool131 { get; set; }
        public bool bool132 { get; set; }
        public bool bool133 { get; set; }
        public bool bool134 { get; set; }
        public bool bool135 { get; set; }
        public bool bool136 { get; set; }
        public bool bool137 { get; set; }
        public bool bool138 { get; set; }
        public bool bool139 { get; set; }
        public bool bool140 { get; set; }
        public bool bool141 { get; set; }
        public bool bool142 { get; set; }
        public bool bool143 { get; set; }
        public bool bool144 { get; set; }
        public bool bool145 { get; set; }
        public bool bool146 { get; set; }
        public bool bool147 { get; set; }
        public bool bool148 { get; set; }
        public bool bool149 { get; set; }
        public bool bool150 { get; set; }
        public bool bool151 { get; set; }
        public bool bool152 { get; set; }
        public bool bool153 { get; set; }
        public bool bool154 { get; set; }
        public bool bool155 { get; set; }
        public bool bool156 { get; set; }
        public bool bool157 { get; set; }
        public bool bool158 { get; set; }
        public bool bool159 { get; set; }
        public bool bool160 { get; set; }

        public bool Divertores { get; set; }

        public bool Emergencia1 { get; set; }
        public bool Emergencia2 { get; set; }
        public bool Emergencia3 { get; set; }

        public bool FullLine1 { get; set; }
        public bool FullLine2 { get; set; }
        public bool FullLine3 { get; set; }

    }
}
